export const QUESTION_TYPE_DATE_PICKER = "DATE_PICKER";
export const QUESTION_TYPE_INPUT = "INPUT";
export const QUESTION_TYPE_TEXTAREA = "TEXTAREA";
export const QUESTION_TYPE_RADIO = "RADIO";
export const QUESTION_TYPE_CHECKBOX = "CHECKBOX";
export const QUESTION_TYPE_SELECT = "SELECT";
export const QUESTION_TYPE_SIGNATURE = "SIGNATURE";
export const QUESTION_TYPE_CUSTOMER_CONSENT_AND_ACKNOWLEDGMENT =
  "CUSTOMER_CONSENT_AND_ACKNOWLEDGMENT";
